# Generated by Django 3.2.6 on 2022-02-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20220204_0145'),
        ('profiles', '0006_auto_20220204_0329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProducts',
            new_name='CartProduct',
        ),
    ]
