# Generated by Django 4.0.2 on 2022-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
