# Generated by Django 4.0.2 on 2022-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_close_time_alter_vendor_open_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='location',
            new_name='LAT',
        ),
        migrations.AddField(
            model_name='vendor',
            name='LONG',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
