# Generated by Django 3.2.6 on 2022-02-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
